Repository platformio/platformio-atom-ide-terminal, pull requests merged in 2019-02, with the labels that each got.

#644 task: add github issue/pr templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#646 ghtemplates: minor issue template changes
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#645 add solarized-light closes #491
  lib/platformio-ide-terminal.coffee
  styles/themes.less
  styles/themes/solarized-light.less
Labels: enhancement

#649 contributors: add community contributors
  package.json
Labels: documentation / readmes

#651 fix typo: missing comma in contributors
  package.json
Labels: cleanup

#653 keymap remove unmappable item de2cc2e
  keymaps/platformio-ide-terminal.cson
Labels: cleanup

#564 Mac conflict shortcut conflict.
  keymaps/platformio-ide-terminal.cson
Labels: bug fix
